export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT"

export const FETCH_CHAT_REQUEST = "FETCH_CHAT_REQUEST"
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS"
export const FETCH_CHAT_FAILURE = "FETCH_CHAT_FAILURE"

export const POST_MESSAGE_REQUEST = "POST_MESSAGE_REQUEST"
export const POST_MESSAGE_SUCCESS = "POST_MESSAGE_SUCCESS"
export const POST_MESSAGE_ERROR = "POST_MESSAGE_ERROR"

export const PUT_MESSAGE_REQUEST = "PUT_MESSAGE_REQUEST"
export const PUT_MESSAGE_SUCCESS = "PUT_MESSAGE_SUCCESS"
export const PUT_MESSAGE_ERROR = "PUT_MESSAGE_ERROR"